      ******************************************************************
      * Created: Wed, 21 Feb 2024 08:47:49 GMT
      * Generated by: IBM watsonx Code Assistant for Z Refactoring
      * Assistant
      * Workbook name: PIFFS_refactored
      * Workbook id: 3a97c0ea-776e-47cc-bbc5-5cf142a451d5
      * Project: $clientCOBOL_019d5f04-760e-4a36-991f-c9a07adca0c5
      ******************************************************************

       IDENTIFICATION DIVISION.
       PROGRAM-ID. Refactor.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  ORSS0400-AREA.
           02 ORSS0400-SQLCA          PIC X(136).
           02 F-4 REDEF-4INES ORSS0400-SQLCA.
              03 F1                   PIC  X(12).
              03 ORSS0400-SQLCD       PIC S9(09)   COMP.
              03 F2                   PIC  X(120).
           02 ORSS0400-SYSID          PIC  X(03).
           02 ORSS0400-CLERK          PIC  X(05).
           02 ORSS0400-TABNM          PIC  X(30).
           02 ORSS0400-SSN            PIC  9(12).
           02 ORSS0400-SSN-X REDEFINES ORSS0400-SSN
                                      PIC  X(12).
           02 ORSS0400-TRNID          PIC  X(04).
       01  FLIP-AREA.
         02  FLIP-B.
           03  TWA-FLIP-B-LENGTH            PIC S9(4) COMP SYNC.
           03  TWA-FLIP-B-OUT.
               05  TWA-SPEC-ID-NUM-OUT-R REDEFINES TWA-SPEC-ID-NUM-OUT.
                   10  TWA-SPEC-ID-NUM-OUT-12    PIC 9(12).
               05  TWA-NAT-CERT-NUM-OUT          PIC X(9).
               05  TWA-PAY-FREQ-OUT              PIC X(2).
               05  TWA-LOC-CODE-OUT              PIC X(3).
               05  TWA-SEX-CODE-OUT              PIC X(1).
               05  TWA-NAT-CODE-OUT              PIC X(3).
               05  TWA-TERM-ACT-DATE-OUT.
                   10  TWA-TRMAC-DD-OUT          PIC XX.
                   10  TWA-TRMAC-MM-OUT          PIC XX.
                   10  TWA-TRMAC-YYYY-OUT        PIC X(4).
               05  TWA-MAR-STAT-OUT              PIC X(2).
               05  TWA-BILL-FREQ-OUT             PIC X(2).
               05  TWA-BILL-TYPE-OUT             PIC X(2).
               05  TWA-ACTV-CODE-OUT             PIC X(2).
               05  TWA-REC-TYPE-OUT              PIC X(2).
               05  TWA-BLOCK-CODE-OUT            PIC X(01).
               05  TWA-CHD-AFT-RET-OUT           PIC X(02).
               05  TWA-FIL-NUM-OUT-R    REDEFINES TWA-FIL-NUM-OUT.
                   10  TWA-FIL-NUM-OUT-2         PIC 9(02).
                   10  TWA-FIL-NUM-OUT-9         PIC 9(09).
               05  TWA-50KD-1992-OUT             PIC X(2).
               05  TWA-DED-NOT-PD-OUT            PIC XX.
               05  TWA-PIS-NUM-OUT               PIC X(11).
               05  TWA-CHILD-NO4-OUT             PIC 9(2).
               05  TWA-CHILD-NO3-OUT             PIC 9(2).
               05  TWA-BANK-PAY-METH-CODE-OUT    PIC X(2).
               05  TWA-BANK-BR-AGY-NUM-OUT       PIC X(4).
               05  TWA-BANK-PAYEE-ACCT-NUM-OUT   PIC X(30).
           03  TWA-FLIP-B-IN.
               05  TWA-SPEC-ID-NUM-IN-R REDEFINES TWA-SPEC-ID-NUM-IN.
                   10  TWA-SPEC-ID-NUM-IN-12     PIC 9(12).
               05  TWA-BANK-PAYEE-ACCT-NUM-IN    PIC X(30).
               05  TWA-BANK-BR-AGY-NUM-IN        PIC X(4).
               05  TWA-BANK-PAY-METH-CODE-IN     PIC X(2).
               05  TWA-CHILD-NO3-IN              PIC 9(2).
               05  TWA-CHILD-NO4-IN              PIC 9(2).
               05  TWA-PIS-NUM-IN                PIC X(11).
               05  TWA-DED-NOT-PD-IN             PIC XX.
               05  TWA-50KD-1992-IN              PIC X(2).
               05  TWA-FIL-NUM-IN                PIC 9(11).
               05  TWA-FIL-NUM-IN-R     REDEFINES TWA-FIL-NUM-IN.
                   10  TWA-FIL-NUM-IN-2          PIC 9(02).
               05  TWA-CHD-AFT-RET-IN            PIC X(02).
               05  TWA-BLOCK-CODE-IN             PIC X(01).
               05  TWA-REC-TYPE-IN               PIC X(2).
               05  TWA-ACTV-CODE-IN              PIC X(2).
               05  TWA-BILL-TYPE-IN              PIC X(2).
               05  TWA-BILL-FREQ-IN              PIC X(2).
               05  TWA-MAR-STAT-IN               PIC X(2).
               05  TWA-TERM-ACT-DATE-IN          PIC X(8).
               05  TWA-NAT-CODE-IN               PIC X(3).
               05  TWA-SEX-CODE-IN               PIC X(1).
               05  TWA-LOC-CODE-IN               PIC X(3).
               05  TWA-PAY-FREQ-IN               PIC X(2).
               05  TWA-NAT-CERT-NUM-IN           PIC X(9).
         02  FLIP-A.
           03  TWA-FLIP-A-LENGTH     PIC S9(4) COMP SYNC.
           03  TWA-FLIP-A-IN.
               05  TWA-ER-REG-NUM-IN              PIC X(7).
               05  TWA-SYS-ENTRY-DATE-IN         PIC X(8).
               05  TWA-NEXT-ACT-DATE-IN          PIC X(8).
               05  TWA-LAST-ACCT-DATE-IN         PIC X(8).
               05  TWA-LAST-FM-DATE-IN           PIC X(8).
               05  TWA-REG-EFF-DATE-IN           PIC X(8).
               05  TWA-PAY-DAY-IN                PIC X(2).
               05  TWA-BIRTH-DATE-IN             PIC X(8).
               05  TWA-DEATH-DATE-IN             PIC X(8).
               05  TWA-NAT-EFF-DATE-IN           PIC X(8).
               05  TWA-COLL-DAY-IN               PIC X(2).
               05  TWA-OCC-CODE-IN  REDEFINES  TWA-ER-BUS-TYPE-IN
                                                 PIC X(4).
               05  TWA-FORM-REC-DATE-IN          PIC X(8).
               05  TWA-SOURCE-IN                 PIC X(2).
               05  TWA-CHILD-NO1-IN              PIC 9(2).
               05  TWA-CHILD-NO2-IN              PIC 9(2).
               05  TWA-20KD-1992-IN              PIC X(2).
           03  TWA-FLIP-A-OUT.
               05  TWA-CHILD-NO1-OUT             PIC 9(2).
               05  TWA-SOURCE-OUT                PIC X(2).
               05  TWA-FORM-REC-DATE-OUT.
                   10  TWA-FORM-REC-DD-OUT       PIC XX.
                   10  TWA-FORM-REC-MM-OUT       PIC XX.
                   10  TWA-FORM-REC-YYYY-OUT     PIC X(4).
               05  TWA-LAST-ACCT-DATE-OUT.
                   10  TWA-LAST-ACCT-DD-OUT      PIC XX.
                   10  TWA-LAST-ACCT-MM-OUT      PIC XX.
                   10  TWA-LAST-ACCT-YYYY-OUT    PIC X(4).
               05  TWA-NEXT-ACT-DATE-OUT.
                   10  TWA-NEXT-ACT-DD-OUT       PIC XX.
                   10  TWA-NEXT-ACT-MM-OUT       PIC XX.
                   10  TWA-NEXT-ACT-YYYY-OUT     PIC X(4).
               05  TWA-OCC-CODE-OUT  REDEFINES  TWA-ER-BUS-TYPE-OUT
                                                 PIC X(4).
               05  TWA-COLL-DAY-OUT              PIC XX.
               05  TWA-NAT-EFF-DATE-OUT.
                   10  TWA-NAT-EFF-DD-OUT        PIC XX.
                   10  TWA-NAT-EFF-MM-OUT        PIC XX.
                   10  TWA-NAT-EFF-YYYY-OUT      PIC X(4).
               05  TWA-SYS-ENTRY-DATE-OUT.
                   10  TWA-SYS-ENTRY-DD-OUT      PIC XX.
                   10  TWA-SYS-ENTRY-MM-OUT      PIC XX.
                   10  TWA-SYS-ENTRY-YYYY-OUT    PIC X(4).
               05  TWA-DEATH-DATE-OUT.
                   10  TWA-DEATH-YYYY-OUT        PIC X(4).
                   10  TWA-DEATH-DD-OUT          PIC XX.
                   10  TWA-DEATH-MM-OUT          PIC XX.
               05  TWA-ER-REG-NUM-OUT            PIC X(7).
               05  TWA-EMP-NUM-OUT               PIC X(11).
               05  TWA-BIRTH-DATE-OUT.
                   10  TWA-BIRTH-DD-OUT          PIC XX.
                   10  TWA-BIRTH-MM-OUT          PIC XX.
                   10  TWA-BIRTH-YYYY-OUT        PIC X(4).
               05  TWA-PAY-DAY-OUT               PIC XX.
               05  TWA-REG-EFF-DATE-OUT.
                   10  TWA-REG-EFF-DD-OUT        PIC XX.
                   10  TWA-REG-EFF-MM-OUT        PIC XX.
                   10  TWA-REG-EFF-YYYY-OUT      PIC X(4).
               05  TWA-20KD-1992-OUT             PIC X(2).
               05  TWA-LAST-FM-DATE-OUT.
                   10  TWA-LAST-FM-MM-OUT        PIC XX.
                   10  TWA-LAST-FM-YYYY-OUT      PIC X(4).
                   10  TWA-LAST-FM-DD-OUT        PIC XX.
               05  TWA-CHILD-NO2-OUT             PIC 9(2).
       01  ABEND-ERR-MSG.
           02 ABEND-ERR-TEXT          PIC X(10).
           02 F-1                       PIC X(01) VALUE SPACES.
           02 ABEND-ERR-EIBDS         PIC X(30).
           02 F-2                       PIC X(01) VALUE SPACES.
           02 F-3                       PIC X(05) VALUE 'åÒãÑ '.
           02 F-5                       PIC X(01) VALUE SPACES.
           02 ABEND-ERR-CODE          PIC X(04).
       01  W-SQLCD                      PIC Z(09)-.
       01  W-SQLCD-C REDEFINES W-SQLCD  PIC X(10).
       01  W-EIBDS                     PIC X(30).
       01  W-DATE                       PIC X(10).
       01  W-DATEX REDEFINES W-DATE.
           02 W-DAY                     PIC 9(02).
           02 W-YEAR                    PIC 9(04).
           02 W-MNTH                    PIC 9(02).
       01  W-DATE-9.
           02 W-YEAR9                   PIC 9(04).
           02 W-MNTH9                   PIC 9(02).
           02 W-DAY9                    PIC 9(02).
       01  W-DATE9 REDEFINES W-DATE-9   PIC 9(08).
       01  GREG-DATE                  PIC X(08).
       01  W-CUR-DATE                 PIC X(02)/X(02)/X(04).
       01  W-TIME                     PIC 99/99/99.
        01  EMPLER-IND                PIC S9(04) COMP.
        01  REGNUM-IND                PIC S9(04) COMP.
        01  ENTDT-IND                 PIC S9(04) COMP.
       01 TCA-FIELD.
           05  TCADCDC.
              10  FILLER                    PIC X(04) VALUE '1511'.
              10  TCADCDC1                  PIC X(03) VALUE SPACES.
           05  W-RESP                     PIC S9(04) COMP.
           05  TCANXTID                  PIC X(04) VALUE SPACES.
           05  TCAPCPI                   PIC X(08) VALUE SPACES.
        01  LACTDT-IND                PIC S9(04) COMP.
       01  CONSTANTS.
             05   W-ER-REG-NUM              PIC 9(07).
             05   W-CIVIL-ID                PIC 9(12).
             05  K-PF10-11.
              10  FILLER                      PIC X(70)  VALUE
                 'åáæÍãáÇ ÛáÇÈãáÇ äÚ ÑÇÓÝÊÓáÇ/ 01ÝÈ ÊÇßíÔáÇ äÚ ÑÇÓÝÊÓáÇ
      -           'ÝÈ ßæäÈáá11 '.
               05  TWA-DROP-NAT-DATE-IN1         PIC X(9).
               05  TWA-DROP-NAT-DATE-IN.
                   10  TWA-DROP-NATYYYY-IN       PIC X(4).
                   10  TWA-DROP-NATMM-IN         PIC XX.
                   10  TWA-DROP-NATDD-IN         PIC XX.
               05  TWA-CIV-EXP-DATE-IN1         PIC X(9).
               05  TWA-CIV-EXP-DATE-IN.
                   10  TWA-CIV-EXPYYYY-IN       PIC X(4).
                   10  TWA-CIV-EXPMM-IN         PIC XX.
                   10  TWA-CIV-EXPDD-IN         PIC XX.
        01  LASFMDT-IND               PIC S9(04) COMP.
        01  REGFDT-IND                PIC S9(04) COMP.
        01  DETHDT-IND                PIC S9(04) COMP.
        01  NCRTF-IND                 PIC S9(04) COMP.
        01  NEFFDT-IND                PIC S9(04) COMP.
        01  RECFDT-IND                PIC S9(04) COMP.
        01  TRMDT-IND                 PIC S9(04) COMP.
       01  FLIP-PTR                   PIC S9(08) COMP.
        01  FRMDT-IND                 PIC S9(04) COMP.
        01  THRD-IND                  PIC S9(04) COMP.
        01  NDRPDT-IND                PIC S9(04) COMP.
        01  CEXPDT-IND                PIC S9(04) COMP.

           EXEC SQL
             INCLUDE SQLCA
           END-EXEC.

       LINKAGE SECTION.

       PROCEDURE DIVISION.
       C0300-INQUIRY  SECTION.
      
           MOVE +0         TO TWAOCCA.
           MOVE LOW-VALUES TO TWARDSW.
      
           MOVE 'ST_MST_EMPLOYF COPYIC'  TO W-EIBDS.
           MOVE TWANUM                   TO T-M-BAS-EE-SSN.
      
           EXEC SQL
                SELECT M_BAS_EE_EMPLOYER_NUM     ,
                       M_BAS_EE_SEC_REG_NUM      ,
                       M_BAS_EE_MAST_REC_CODE    ,
                       M_BAS_EE_LOC_CODE         ,
                       M_BAS_EE_ACT_CODE         ,
                       M_BAS_EE_SYS_ENTRY_DATE   ,
                       M_BAS_EE_SYS_ENTRY_SOURCE ,
                       M_BAS_EE_NEXT_ACT_DATE    ,
                       M_BAS_EE_LAST_ACCT_DATE   ,
                       M_BAS_EE_LAST_FM_DATE     ,
                       M_BAS_EE_BILL_FREQ_CODE   ,
                       M_BAS_EE_BILL_TYPE_CODE   ,
                       M_BAS_EE_BILL_DAY         ,
                       M_BAS_EE_PAY_FREQ_CODE    ,
                       M_BAS_EE_PAY_DAY          ,
                       M_BAS_EE_REG_EFF_DATE     ,
                       M_BAS_EE_BIRTH_DATE       ,
                       M_BAS_EE_DEATH_DATE       ,
                       M_BAS_EE_OCC_CODE         ,
                       M_BAS_EE_SEX_CODE         ,
                       M_BAS_EE_MAR_STAT_CODE    ,
                       M_BAS_EE_PIS_NUM          ,
                       M_BAS_EE_CIVIL_ID         ,
                       M_BAS_EE_NAT_CODE         ,
                       M_BAS_EE_NAT_CERT_NUM     ,
                       M_BAS_EE_NAT_EFF_DATE     ,
                       M_BAS_EE_DED_DED_NT_PD    ,
                       M_BAS_EE_TERM_ACT_DATE    ,
                       M_BAS_EE_20KD_1992        ,
                       M_BAS_EE_50KD_1992        ,
                       M_BAS_EE_CHILD_5KD_89     ,
                       M_BAS_EE_CHILD_10KD_89    ,
                       M_BAS_EE_CHILD_30KD_A89   ,
                       M_BAS_EE_CHILD_30KD_B89   ,
                       M_BAS_EE_FILING_NUMBER    ,
                       M_BAS_EE_CHLD_RETIRE    ,
                       M_BAS_EE_OVR_MAX_941231 ,
                       M_BAS_EE_BLOCK_CODE     ,
                       M_BAS_EE_FORM_REC_DATE ,
                       M_BAS_EE_DROP_NAT_DATE,
                       M_BAS_EE_CV_EXP_DATE
                INTO  :T-M-BAS-EE-EMPLOYER-NUM:EMPLER-IND   ,
                      :T-M-BAS-EE-SEC-REG-NUM:REGNUM-IND    ,
                      :T-M-BAS-EE-MAST-REC-CODE      ,
                      :T-M-BAS-EE-LOC-CODE           ,
                      :T-M-BAS-EE-ACT-CODE           ,
                      :T-M-BAS-EE-SYS-ENTRY-DATE:ENTDT-IND ,
                      :T-M-BAS-EE-SYS-ENTRY-SOURCE          ,
                      :T-M-BAS-EE-NEXT-ACT-DATE             ,
                      :T-M-BAS-EE-LAST-ACCT-DATE:LACTDT-IND ,
                      :T-M-BAS-EE-LAST-FM-DATE:LASFMDT-IND  ,
                      :T-M-BAS-EE-BILL-FREQ-CODE            ,
                      :T-M-BAS-EE-BILL-TYPE-CODE            ,
                      :T-M-BAS-EE-BILL-DAY                  ,
                      :T-M-BAS-EE-PAY-FREQ-CODE             ,
                      :T-M-BAS-EE-PAY-DAY                   ,
                      :T-M-BAS-EE-REG-EFF-DATE:REGFDT-IND ,
                      :T-M-BAS-EE-BIRTH-DATE              ,
                      :T-M-BAS-EE-DEATH-DATE:DETHDT-IND   ,
                      :T-M-BAS-EE-OCC-CODE                ,
                      :T-M-BAS-EE-SEX-CODE                ,
                      :T-M-BAS-EE-MAR-STAT-CODE           ,
                      :T-M-BAS-EE-PIS-NUM                 ,
                      :T-M-BAS-EE-CIVIL-ID                ,
                      :T-M-BAS-EE-NAT-CODE                ,
                      :T-M-BAS-EE-NAT-CERT-NUM:NCRTF-IND  ,
                      :T-M-BAS-EE-NAT-EFF-DATE:NEFFDT-IND ,
                      :T-M-BAS-EE-DED-DED-NT-PD           ,
                      :T-M-BAS-EE-TERM-ACT-DATE:TRMDT-IND ,
                      :T-M-BAS-EE-20KD-1992               ,
                      :T-M-BAS-EE-50KD-1992               ,
                      :T-M-BAS-EE-CHILD-5KD-89            ,
                      :T-M-BAS-EE-CHILD-10KD-89           ,
                      :T-M-BAS-EE-CHILD-30KD-A89          ,
                      :T-M-BAS-EE-CHILD-30KD-B89          ,
                      :T-M-BAS-EE-FILING-NUMBER           ,
                      :T-M-BAS-EE-CHLD-RETIRE             ,
                      :T-M-BAS-EE-OVR-MAX-941231          ,
                      :T-M-BAS-EE-BLOCK-CODE              ,
                      :T-M-BAS-EE-FORM-REC-DATE:FRMDT-IND ,
                      :T-M-BAS-EE-DROP-NAT-DATE:NDRPDT-IND,
                      :T-M-BAS-EE-CV-EXP-DATE:CEXPDT-IND
                FROM ST_MST_EMPLOYEE_BASIC
                WHERE     M_BAS_EE_SSN = :T-M-BAS-EE-SSN
                 ORDER BY M_BAS_EE_SSN   ASC
                          FETCH FIRST 1 ROW ONLY
                END-EXEC
      
                PERFORM DB2-ERROR.
                IF SQLCODE  =  +0
                   NEXT SENTENCE
                ELSE
                IF SQLCODE  = +100
                   MOVE 'ÝáãáÇìáÚÏæÌæãÑíÛáÌÓáÇ' TO ERRMSG1O
                   MOVE HIGH-VALUES             TO TWAERROR
                   GO TO C0300-INQUIRY-EXIT
                ELSE
                   MOVE 'åíÓÇÓÃ ÊÇäÇíÈ Ýáã Úã áãÇÚÊáÇÈ ÃØÎ' TO ERRMSG1O
                   MOVE HIGH-VALUES                         TO TWAERROR
                   GO TO C0300-INQUIRY-EXIT
                END-IF.
      
      *DB2 MOVE  10  TO  TWATRLNO.
      *DB2 MOVE  01  TO  TWARELNO.
      
      *DB2 CALL 'CCOBADDR'        USING  SFCOCCUR
      *DB2                               OCCR-TBL-PTR.
      *DB2 MOVE OCCR-TBL-PTR-R  TO  TWAOCCA.
      
      *DB2 PERFORM S0100-LOCATE-TRAILER.
      
      **   MOVE  TWATLADR     TO   BASIC-PTR-R.
      *DB2 MOVE  TWAGETAD     TO   BASIC-PTR-R.
      *DB2 MOVE  BASIC-PTR-R  TO  TWA-BASIC-DATA-BAR.
      *DB2
      *DB2 SET BASIC-PTR TO ADDRESS OF MASTER-RECORD-BASIC-DATA.
      
      *DB2 IF  TWARTCD  EQUAL TO ZERO
      *DB2
      *DB2     NEXT SENTENCE
      *DB2 ELSE
      *DB2     MOVE 'ÝáãáÇìáÚÏæÌæãÑíÛáÌÓáÇ' TO ERRMSG1O
      *DB2     MOVE HIGH-VALUES TO TWAERROR
      *DB2     GO TO C0300-INQUIRY-EXIT.
      
           PERFORM C0301-SET-REC-TYPE.
      
           IF  EE-RECORD
             PERFORM C0550-BUILD-BANK-INFO
           ELSE
             NEXT SENTENCE.
      
           PERFORM  C0600-FLIP-AND-BUILD-SCREEN.
      
           PERFORM  C0400-BUILD-NAME.
      
           PERFORM  C0310-FORMAT-SCREEN-BASIC-DATA.

       C0300-INQUIRY-EXIT.  EXIT.

       C0301-SET-REC-TYPE  SECTION.
      
           MOVE  LOW-VALUES  TO  TWA-SSN-TYPE
                                 TWA-BENEF-SW.
      
           MOVE T-M-BAS-EE-MAST-REC-CODE  TO TWA-MAST-CODE.
      *DB2 MOVE T-M-BAS-EE-MAST-REC-CODE  (1)  TO TWA-MAST-CODE.
      
           IF  TWA-MAST-CODE   EQUAL  TB101-MAST-ER
      
               MOVE  'R'  TO  TWA-SSN-TYPE
           ELSE
               IF  TWA-MAST-CODE  EQUAL TB101-MAST-EE             OR
                   TWA-MAST-CODE  EQUAL TB101-MAST-EE-PENR        OR
                   TWA-MAST-CODE  EQUAL TB101-MAST-EE-BENEF       OR
                   TWA-MAST-CODE  EQUAL TB101-MAST-EE-VOL-INS     OR
                   TWA-MAST-CODE  EQUAL TB101-MAST-BENEF-SELF-EMP OR
                   TWA-MAST-CODE  EQUAL TB101-MAST-SELF-EMP       OR
                   TWA-MAST-CODE  EQUAL  TB101-LEAV-IND-EE
                   MOVE  'E'  TO  TWA-SSN-TYPE
               ELSE
                   NEXT  SENTENCE.
      
           IF  TWA-MAST-CODE EQUAL TB101-MAST-EE-PENR    OR
               TWA-MAST-CODE EQUAL TB101-MAST-PENR       OR
               TWA-MAST-CODE EQUAL TB101-MAST-PENR-BENEF
      
               MOVE 'P' TO TWA-SSN-TYPE1
           ELSE
               NEXT SENTENCE.
      
           IF  TWA-MAST-CODE  EQUAL  TB101-MAST-EE-BENEF        OR
               TWA-MAST-CODE  EQUAL  TB101-MAST-PENR-BENEF      OR
               TWA-MAST-CODE  EQUAL  TB101-MAST-BENEF           OR
               TWA-MAST-CODE  EQUAL  TB101-MAST-BENEF-SELF-EMP  OR
               TWA-MAST-CODE  EQUAL  TB101-MAST-BENEF-VOL-INS
      
               MOVE 'B' TO TWA-BENEF-SW
           ELSE
               NEXT SENTENCE.

       C0301-SET-REC-TYPE-EXIT.  EXIT.

       C0310-FORMAT-SCREEN-BASIC-DATA  SECTION.
      
      **   MOVE TWATLADR TO M-BAS-DATA-BAR.
      **   MOVE TWATLADR TO TWA-BASIC-DATA-BAR.
      *    MOVE BASIC-PTR-R TO
      *                        TWA-BASIC-DATA-BAR.
      
           MOVE TWA-EMP-NUM-OUT        TO SSNO.
      
           MOVE TWA-SYS-ENTRY-YYYY-OUT TO SENTRYYO.
           MOVE TWA-SYS-ENTRY-MM-OUT   TO SENTRMMO.
           MOVE TWA-SYS-ENTRY-DD-OUT   TO SENTRDDO.
      
           MOVE TWA-NEXT-ACT-YYYY-OUT  TO NXACTYYO.
           MOVE TWA-NEXT-ACT-MM-OUT    TO NXACTMMO.
           MOVE TWA-NEXT-ACT-DD-OUT    TO NXACTDDO.
      
           MOVE TWA-LAST-ACCT-YYYY-OUT TO LACCTYYO.
           MOVE TWA-LAST-ACCT-MM-OUT   TO LACCTMMO.
           MOVE TWA-LAST-ACCT-DD-OUT   TO LACCTDDO.
      
           MOVE TWA-LAST-FM-YYYY-OUT   TO LFMYYO.
           MOVE TWA-LAST-FM-MM-OUT     TO LFMMMO.
           MOVE TWA-LAST-FM-DD-OUT     TO LFMDDO.
      
           MOVE TWA-REG-EFF-YYYY-OUT   TO REGYYO.
           MOVE TWA-REG-EFF-MM-OUT     TO REGMMO.
           MOVE TWA-REG-EFF-DD-OUT     TO REGDDO.
      
           MOVE TWA-PAY-DAY-OUT        TO DTPAYMTO.
      
           MOVE TWA-BIRTH-YYYY-OUT     TO DOBYYO.
           MOVE TWA-BIRTH-MM-OUT       TO DOBMMO.
           MOVE TWA-BIRTH-DD-OUT       TO DOBDDO.
      
           MOVE TWA-DEATH-YYYY-OUT     TO DEATHYYO.
           MOVE TWA-DEATH-MM-OUT       TO DEATHMMO.
           MOVE TWA-DEATH-DD-OUT       TO DEATHDDO.
      

           MOVE FUNCTION REVERSE(TWA-DROP-NATYYYY-IN) TO NTDRPYYO.
           MOVE FUNCTION REVERSE(TWA-DROP-NATMM-IN) TO NTDRPMMO.
           MOVE FUNCTION REVERSE(TWA-DROP-NATDD-IN) TO NTDRPDDO.


           MOVE FUNCTION REVERSE(TWA-CIV-EXPYYYY-IN) TO CIVEXPYO.
           MOVE FUNCTION REVERSE(TWA-CIV-EXPMM-IN) TO   CIVEXPMO.
           MOVE FUNCTION REVERSE(TWA-CIV-EXPDD-IN) TO   CIVEXPDO.

           MOVE TWA-NAT-EFF-YYYY-OUT   TO NTISSYYO.
           MOVE TWA-NAT-EFF-MM-OUT     TO NTISSMMO.
           MOVE TWA-NAT-EFF-DD-OUT     TO NTISSDDO.
      
           MOVE TWA-SOURCE-OUT         TO SOURCETO.
           MOVE TWA-FORM-REC-YYYY-OUT  TO FORMRYYO.
           MOVE TWA-FORM-REC-MM-OUT    TO FORMRMMO.
           MOVE TWA-FORM-REC-DD-OUT    TO FORMRDDO.
           MOVE TWA-CHILD-NO1-OUT      TO CHLD1NOO.
           MOVE TWA-CHILD-NO2-OUT      TO CHLD2NOO.
           MOVE TWA-CHILD-NO3-OUT      TO CHLD3NOO.
           MOVE TWA-CHILD-NO4-OUT      TO CHLD4NOO.
      
           MOVE TWA-COLL-DAY-OUT       TO DATCOLLO.
           MOVE TWA-REC-TYPE-OUT       TO TYPRECO.
           MOVE TWA-ACTV-CODE-OUT      TO ACTCODEO.
           MOVE TWA-BILL-TYPE-OUT      TO TYPCOLLO.
           MOVE TWA-BILL-FREQ-OUT      TO FRQCOLLO.
           MOVE TWA-MAR-STAT-OUT       TO STATUSO.
           MOVE TWA-NAT-CODE-OUT       TO NATNLTYO.
           MOVE TWA-SEX-CODE-OUT       TO SEXO.
      
           MOVE TWA-LOC-CODE-OUT       TO LOCO.
           MOVE TWA-OCC-CODE-OUT       TO BUSCODEO.
           MOVE TWA-PAY-FREQ-OUT       TO PAYFREQO.
           MOVE TWA-NAT-CERT-NUM-OUT   TO NTLCERTO.
           MOVE TWA-20KD-1992-OUT      TO KID20KDO.
           MOVE TWA-50KD-1992-OUT      TO KID50KDO.
      
           MOVE TWA-FIL-NUM-OUT-9      TO FILING1O.
           IF   TWA-FIL-NUM-IN-2  IS GREATER THAN ZERO
                MOVE TWA-FIL-NUM-OUT-2 TO FILING2O
                MOVE '/'               TO FILINGSO.
      
      
           MOVE TWA-CHD-AFT-RET-OUT    TO CHLDRTOO.
      
           MOVE TWA-BLOCK-CODE-OUT     TO BLOCKCDO.
      
           IF  ER-RECORD
               NEXT SENTENCE
           ELSE
      ****     MOVE TWA-SPEC-ID-NUM-OUT    TO SPECNUMO.
               MOVE TWA-SPEC-ID-NUM-OUT-12 TO SPECNUMO.
               MOVE TWA-TRMAC-YYYY-OUT     TO TRMACYYO.
               MOVE TWA-TRMAC-MM-OUT       TO TRMACMMO.
               MOVE TWA-TRMAC-DD-OUT       TO TRMACDDO.
           SKIP3
           IF  EE-RECORD
               IF  TWA-BANKSW EQUAL LOW-VALUES
                   MOVE TWA-BANK-PAYEE-ACCT-NUM-OUT   TO ACCTNUMO
                   MOVE TWA-BANK-BR-AGY-NUM-OUT       TO BANKNUMO
                   MOVE TWA-BANK-PAY-METH-CODE-OUT    TO TYPPYMTO
               ELSE
                   NEXT SENTENCE
           ELSE
               NEXT SENTENCE.
      
           MOVE TWA-ER-REG-NUM-OUT   TO REGNUMO.
           MOVE TWA-PIS-NUM-OUT      TO PISNUMO.
           MOVE TWA-DED-NOT-PD-OUT   TO DEDNTPDO.

       C0310-FORMAT-EXIT.  EXIT.

       C0400-BUILD-NAME  SECTION.
      
             PERFORM C0410-EXPAND-EE-NAME.

       C0400-NAME-EXIT.  EXIT.

       C0410-EXPAND-EE-NAME  SECTION.
      
           MOVE 'ST_MST_NAME'  TO W-EIBDS.
           MOVE TWANUM         TO T-M-NAME-SSN.
      
           EXEC SQL
                SELECT M_NAME_TRLR_SEQ_NUM       ,
                       M_NAME_TYPE_CODE          ,
                       M_NAME_FIRST              ,
                       M_NAME_MIDDLE             ,
                       M_NAME_THIRD              ,
                       M_NAME_FAMILY
                INTO  :T-M-NAME-TRLR-SEQ-NUM     ,
                      :T-M-NAME-TYPE-CODE        ,
                      :T-M-NAME-FIRST            ,
                      :T-M-NAME-MIDDLE           ,
                      :T-M-NAME-THIRD:THRD-IND   ,
                      :T-M-NAME-FAMILY
                FROM ST_MST_NAME
                WHERE     M_NAME_SSN = :T-M-NAME-SSN
                 AND      M_NAME_TYPE_CODE = '20'
                 ORDER BY M_NAME_TRLR_SEQ_NUM ASC
                          FETCH FIRST 1 ROW ONLY
                END-EXEC
      
                PERFORM DB2-ERROR
                IF SQLCODE = +0
                   MOVE FUNCTION REVERSE
                                  (T-M-NAME-FAMILY) TO W-NAME4
                   IF THRD-IND = +0
                      MOVE FUNCTION REVERSE
                                  (T-M-NAME-THIRD)  TO W-NAME3
                   END-IF
                   MOVE FUNCTION REVERSE
                                  (T-M-NAME-MIDDLE) TO W-NAME2
                   MOVE FUNCTION REVERSE
                                  (T-M-NAME-FIRST)  TO W-NAME1
                   MOVE W-NAME  TO NAMEO
                ELSE
                IF SQLCODE = +100
                   MOVE 'ST_MST_NAME' TO  W-EIBDS
                   MOVE TWANUM        TO  T-M-NAME-SSN
      
                   EXEC SQL
                     SELECT M_NAME_TRLR_SEQ_NUM       ,
                            M_NAME_TYPE_CODE          ,
                            M_NAME_FIRST              ,
                            M_NAME_MIDDLE             ,
                            M_NAME_THIRD              ,
                            M_NAME_FAMILY
                     INTO  :T-M-NAME-TRLR-SEQ-NUM     ,
                           :T-M-NAME-TYPE-CODE        ,
                           :T-M-NAME-FIRST            ,
                           :T-M-NAME-MIDDLE           ,
                           :T-M-NAME-THIRD:THRD-IND   ,
                           :T-M-NAME-FAMILY
                     FROM ST_MST_NAME
                     WHERE     M_NAME_SSN = :T-M-NAME-SSN
                     ORDER BY M_NAME_TRLR_SEQ_NUM ASC
                          FETCH FIRST 1 ROW ONLY
                   END-EXEC
      
                   PERFORM DB2-ERROR
                   IF SQLCODE = +0
                      MOVE FUNCTION REVERSE
                                  (T-M-NAME-FAMILY) TO W-NAME4
                      IF THRD-IND = +0
                         MOVE FUNCTION REVERSE
                                  (T-M-NAME-THIRD)  TO W-NAME3
                      END-IF
                      MOVE FUNCTION REVERSE
                                  (T-M-NAME-MIDDLE) TO W-NAME2
                      MOVE FUNCTION REVERSE
                                  (T-M-NAME-FIRST)  TO W-NAME1
                      MOVE W-NAME  TO NAMEO
                   ELSE
                   IF SQLCODE = +100
                      MOVE  HIGH-VALUES               TO TWAERROR
                      MOVE 'ÏæÌæã ÑíÛ ãÓáÇ'           TO ERRMSG1O
                      PERFORM D0000-FINAL
                   ELSE
                      MOVE  HIGH-VALUES               TO TWAERROR
                      MOVE 'ãÓáÇ Ýáã Úã áãÇÚÊáÇÈ ÃØÎ' TO ERRMSG1O
                      PERFORM D0000-FINAL
                ELSE
                   MOVE  HIGH-VALUES               TO TWAERROR
                   MOVE 'ãÓáÇ Ýáã Úã áãÇÚÊáÇÈ ÃØÎ' TO ERRMSG1O
                   PERFORM D0000-FINAL
                END-IF.

       C0550-BUILD-BANK-INFO SECTION.
      
           MOVE LOW-VALUES TO TWARDSW.
      
           MOVE 'ST_MST_BANK_PAY'  TO  W-EIBDS.
           MOVE TWANUM             TO  T-M-BANK-PAY-SSN.
      
           EXEC SQL
                SELECT  M_BANK_PAY_METHOD_CODE      ,
                        M_BANK_PAY_PAYEE_ACCT_NUM   ,
                        M_BANK_PAY_BANK_CODE        ,
                        M_BANK_PAY_BANK_BR_AGY_CODE
                INTO  :T-M-BANK-PAY-METHOD-CODE     ,
                      :T-M-BANK-PAY-PAYEE-ACCT-NUM  ,
                      :T-M-BANK-PAY-BANK-CODE       ,
                      :T-M-BANK-PAY-BANK-BR-AGY-CODE
                FROM ST_MST_BANK_PAY
                WHERE
                    M_BANK_PAY_SSN   =  :T-M-BANK-PAY-SSN
                                    AND
                    M_BANK_PAY_END_DATE IS NULL
                ORDER BY M_BANK_PAY_SSN ,
                         M_BANK_PAY_TRLR_SEQ_NUM DESC
                 FETCH FIRST 1 ROW ONLY
      
            END-EXEC.
      
                PERFORM DB2-ERROR.
                IF SQLCODE  =  +0
                   NEXT SENTENCE
                ELSE
                IF SQLCODE  =  +100
                   MOVE 'ÏæÌæã ÑíÛ ßäÈáÇ áÌÓ '      TO ERRMSG1O
                ELSE
                   MOVE  HIGH-VALUES                TO TWAERROR
                   MOVE 'ßäÈáÇ Ýáã Úã áãÇÚÊáÇÈ ÃØÎ' TO ERRMSG1O
                   PERFORM D0000-FINAL
                END-IF.

       C0550-BUILD-BANK-INFO-EXIT.
           EXIT.

       C0600-FLIP-AND-BUILD-SCREEN  SECTION.
      
           CALL 'CCOBADDR'  USING  TWA-FLIP-A-LENGTH  FLIP-PTR.
           MOVE  FLIP-PTR   TO  TCTTE-ADDR4.
      
           MOVE FLIP-PTR    TO TCTTE-ADDR4.
           ADD FLIP-PTR 2   GIVING TCTTE-ADDR2.
           ADD FLIP-PTR 116 GIVING TCTTE-ADDR3.
      
           MOVE 114  TO  TWA-FLIP-A-LENGTH.
      
           IF ENTDT-IND = +0
             MOVE T-M-BAS-EE-SYS-ENTRY-DATE  TO W-DATE
             PERFORM C9000-VALDT
             MOVE W-DATE9                    TO TWA-SYS-ENTRY-DATE-IN.
      *DB2 MOVE M-BAS-DATA-SYS-ENTRY-DATE (1) TO TWA-SYS-ENTRY-DATE-IN.
      
           MOVE T-M-BAS-EE-SYS-ENTRY-SOURCE  TO TWA-SOURCE-IN.
      *DB2 MOVE M-BAS-DATA-SYS-ENTRY-SOURCE (1) TO TWA-SOURCE-IN.
      
           MOVE T-M-BAS-EE-NEXT-ACT-DATE     TO W-DATE.
           PERFORM C9000-VALDT.
           MOVE W-DATE9                      TO TWA-NEXT-ACT-DATE-IN.
      *DB2 MOVE M-BAS-DATA-NEXT-ACT-DATE  (1) TO TWA-NEXT-ACT-DATE-IN.
      
           IF LACTDT-IND = +0
             MOVE T-M-BAS-EE-LAST-ACCT-DATE TO W-DATE
             PERFORM C9000-VALDT
             MOVE W-DATE9                   TO TWA-LAST-ACCT-DATE-IN.
      *DB2 MOVE M-BAS-DATA-LAST-ACCT-DATE (1) TO TWA-LAST-ACCT-DATE-IN.
      
           IF LASFMDT-IND = +0
             MOVE T-M-BAS-EE-LAST-FM-DATE  TO W-DATE
             PERFORM C9000-VALDT
             MOVE W-DATE9                  TO TWA-LAST-FM-DATE-IN.
      *DB2 MOVE M-BAS-DATA-LAST-FM-DATE   (1) TO TWA-LAST-FM-DATE-IN.
      
           IF REGFDT-IND = +0
             MOVE T-M-BAS-EE-REG-EFF-DATE TO W-DATE
             PERFORM C9000-VALDT
             MOVE W-DATE9                 TO TWA-REG-EFF-DATE-IN.
      *DB2 MOVE M-BAS-DATA-REG-EFF-DATE   (1) TO TWA-REG-EFF-DATE-IN.
      
           MOVE T-M-BAS-EE-LOC-CODE       TO TWA-LOC-CODE-IN.
      *DB2 MOVE M-BAS-DATA-LOC-CODE       (1) TO TWA-LOC-CODE-IN.
      
           MOVE T-M-BAS-EE-OCC-CODE       TO TWA-OCC-CODE-IN.
      *DB2 MOVE M-BAS-DATA-OCC-CODE       (1) TO TWA-OCC-CODE-IN.
      
           MOVE T-M-BAS-EE-PAY-FREQ-CODE  TO TWA-PAY-FREQ-IN.
      *DB2 MOVE M-BAS-DATA-PAY-FREQ-CODE  (1) TO TWA-PAY-FREQ-IN.
      
           MOVE T-M-BAS-EE-CIVIL-ID       TO W-CIVIL-ID.
           MOVE W-CIVIL-ID                TO TWA-SPEC-ID-NUM-IN-12.
      *    MOVE T-M-BAS-EE-CIVIL-ID       TO TWA-SPEC-ID-NUM-IN.
      *DB2 MOVE M-BAS-DATA-SPEC-ID-NUM    (1) TO TWA-SPEC-ID-NUM-IN.
      
           IF NCRTF-IND = 0
             MOVE T-M-BAS-EE-NAT-CERT-NUM  TO TWA-NAT-CERT-NUM-IN.
      *DB2 MOVE M-BAS-DATA-NAT-CERT-NUM   (1) TO TWA-NAT-CERT-NUM-IN.
      
           IF DETHDT-IND = +0
             MOVE T-M-BAS-EE-DEATH-DATE TO W-DATE
             PERFORM C9000-VALDT
             MOVE W-DATE9               TO TWA-DEATH-DATE-IN.
      *DB2 MOVE M-BAS-DATA-DEATH-DATE     (1) TO TWA-DEATH-DATE-IN.
      
           MOVE T-M-BAS-EE-BIRTH-DATE   TO W-DATE
           PERFORM C9000-VALDT
           MOVE W-DATE9                 TO TWA-BIRTH-DATE-IN.
      *DB2 MOVE M-BAS-DATA-BIRTH-DATE     (1) TO TWA-BIRTH-DATE-IN.
      
           MOVE T-M-BAS-EE-PAY-DAY      TO TWA-PAY-DAY-IN.
      *DB2 MOVE M-BAS-DATA-PAY-DAY        (1) TO TWA-PAY-DAY-IN.
      
           IF  T-M-BAS-EE-CHLD-RETIRE  IS NUMERIC
      
               MOVE  T-M-BAS-EE-CHLD-RETIRE  TO  TWA-CHD-AFT-RET-IN
           ELSE
               MOVE  ZEROES  TO  TWA-CHD-AFT-RET-IN.
      
      
           IF  T-M-BAS-EE-BLOCK-CODE  IS NUMERIC
      
               MOVE  T-M-BAS-EE-BLOCK-CODE   TO  TWA-BLOCK-CODE-IN
           ELSE
               MOVE  ZEROES  TO  TWA-BLOCK-CODE-IN.
      
      
      *DB2 IF  M-BAS-DATA-CHLD-RETIRE (1) IS NUMERIC
      *DB2     MOVE  M-BAS-DATA-CHLD-RETIRE (1)  TO  TWA-CHD-AFT-RET-IN
      *DB2 ELSE
      *DB2     MOVE  ZEROES  TO  TWA-CHD-AFT-RET-IN.
      
           IF   T-M-BAS-EE-FILING-NUMBER   IS NOT NUMERIC
                MOVE ZEROES  TO TWA-FIL-NUM-IN
           ELSE
                MOVE T-M-BAS-EE-FILING-NUMBER  TO TWA-FIL-NUM-IN.
      
      *DB2 IF   M-BAS-DATA-FILING-NUMBER  (1) IS NOT NUMERIC
      *DB2      MOVE ZEROES  TO TWA-FIL-NUM-IN
      *DB2 ELSE
      *DB2      MOVE M-BAS-DATA-FILING-NUMBER  (1) TO TWA-FIL-NUM-IN.
      
      
           IF   T-M-BAS-EE-20KD-1992       IS GREATER THAN ZERO
              MOVE T-M-BAS-EE-20KD-1992      TO TWA-20KD-1992-IN
           ELSE
              MOVE ZEROS                     TO TWA-20KD-1992-IN.
      
      *DB2 IF   M-BAS-DATA-20KD-1992      (1) IS NUMERIC
      *DB2    MOVE M-BAS-DATA-20KD-1992      (1) TO TWA-20KD-1992-IN
      *DB2 ELSE
      *DB2    MOVE ZEROS                         TO TWA-20KD-1992-IN.
      
           IF   T-M-BAS-EE-50KD-1992       IS GREATER THAN ZERO
               MOVE T-M-BAS-EE-50KD-1992      TO TWA-50KD-1992-IN
           ELSE
               MOVE ZEROS                     TO TWA-50KD-1992-IN.
      
      *DB2 IF   M-BAS-DATA-50KD-1992      (1) IS NUMERIC
      *DB2     MOVE M-BAS-DATA-50KD-1992   (1)    TO TWA-50KD-1992-IN
      *DB2 ELSE
      *DB2     MOVE ZEROS                         TO TWA-50KD-1992-IN.
      
      
           IF  RECFDT-IND = +0
              MOVE  T-M-BAS-EE-FORM-REC-DATE   TO   W-DATE
              PERFORM C9000-VALDT
              MOVE  W-DATE9                    TO TWA-FORM-REC-DATE-IN.
      *DB2 IF  M-BAS-DATA-FORM-REC-DATE (1)  IS NUMERIC  AND
      *DB2     M-BAS-DATA-FORM-REC-DATE (1)  GREATER THAN ZERO
      *DB2     MOVE M-BAS-DATA-FORM-REC-DATE (1)
      *DB2                                    TO TWA-FORM-REC-DATE-IN
      *DB2 ELSE
      *DB2     MOVE ZEROS TO TWA-FORM-REC-DATE-IN.
      
           IF  T-M-BAS-EE-CHILD-5KD-89  IS GREATER THAN ZERO
           THEN
               MOVE T-M-BAS-EE-CHILD-5KD-89  TO TWA-CHILD-NO1-IN
           ELSE
               MOVE ZEROES  TO  TWA-CHILD-NO1-IN.
      
      *DB2 IF  M-BAS-DATA-CHILD-5KD-89 (1) IS NUMERIC
      *DB2 THEN
      *DB2     MOVE M-BAS-DATA-CHILD-5KD-89 (1) TO TWA-CHILD-NO1-IN
      *DB2 ELSE
      *DB2     MOVE ZEROES  TO  TWA-CHILD-NO1-IN.
      
           IF  T-M-BAS-EE-CHILD-10KD-89  IS GREATER THAN ZERO
           THEN
               MOVE T-M-BAS-EE-CHILD-10KD-89  TO TWA-CHILD-NO2-IN
           ELSE
               MOVE ZEROES  TO  TWA-CHILD-NO2-IN.
      
      *DB2 IF  M-BAS-DATA-CHILD-10KD-89 (1) IS NUMERIC
      *DB2 THEN
      *DB2     MOVE M-BAS-DATA-CHILD-10KD-89 (1) TO TWA-CHILD-NO2-IN
      *DB2 ELSE
      *DB2     MOVE ZEROES  TO  TWA-CHILD-NO2-IN.
      
           IF  T-M-BAS-EE-CHILD-30KD-A89  IS GREATER THAN ZERO
           THEN
               MOVE T-M-BAS-EE-CHILD-30KD-A89  TO TWA-CHILD-NO3-IN
           ELSE
               MOVE ZEROES  TO  TWA-CHILD-NO3-IN.
      
      *DB2 IF  M-BAS-DATA-CHILD-30KD-A89 (1) IS NUMERIC
      *DB2 THEN
      *DB2     MOVE M-BAS-DATA-CHILD-30KD-A89 (1) TO TWA-CHILD-NO3-IN
      *DB2 ELSE
      *DB2     MOVE ZEROES  TO  TWA-CHILD-NO3-IN.
      
           IF  T-M-BAS-EE-CHILD-30KD-B89  IS GREATER THAN ZERO
           THEN
               MOVE T-M-BAS-EE-CHILD-30KD-B89  TO TWA-CHILD-NO4-IN
           ELSE
               MOVE ZEROES  TO  TWA-CHILD-NO4-IN.
      
      *DB2 IF  M-BAS-DATA-CHILD-30KD-B89 (1) IS NUMERIC
      *DB2 THEN
      *DB2     MOVE M-BAS-DATA-CHILD-30KD-B89 (1) TO TWA-CHILD-NO4-IN
      *DB2 ELSE
      *DB2     MOVE ZEROES  TO  TWA-CHILD-NO4-IN.
      
           IF LACTDT-IND = +0
             MOVE T-M-BAS-EE-LAST-ACCT-DATE TO W-DATE
             PERFORM C9000-VALDT
             MOVE W-DATE9                   TO TWA-LAST-ACCT-DATE-IN.
      *DB2 MOVE M-BAS-DATA-LAST-ACCT-DATE (1) TO TWA-LAST-ACCT-DATE-IN.
      
           IF  TWA-BANKSW EQUAL LOW-VALUES
      
      *DB2     MOVE M-BANK-PAY-BANK-BR-AGY-CODE (1)
               MOVE T-M-BANK-PAY-BANK-BR-AGY-CODE
                                      TO  TWA-BANK-BR-AGY-NUM-IN
      
      *DB2     MOVE M-BANK-PAY-PAYEE-ACCT-NUM (1)
               MOVE T-M-BANK-PAY-PAYEE-ACCT-NUM
      ***ZAI                          TO  W-BANK-ACC-NUM-ALL
      ***ZAI   MOVE W-BANK-ACC-NUM
                                      TO  TWA-BANK-PAYEE-ACCT-NUM-IN
      
      *DB2     MOVE M-BANK-PAY-METHOD-CODE (1)
               MOVE T-M-BANK-PAY-METHOD-CODE
                                      TO  TWA-BANK-PAY-METH-CODE-IN
           ELSE
               NEXT SENTENCE.
      
           IF T-M-BAS-EE-DED-DED-NT-PD  IS NUMERIC
              MOVE T-M-BAS-EE-DED-DED-NT-PD  TO TWA-DED-NOT-PD-IN
           ELSE
              MOVE ZEROS TO TWA-DED-NOT-PD-IN.
      
      *DB2 IF M-BAS-DATA-DED-DED-NT-PD (1) IS NUMERIC
      *DB2    MOVE M-BAS-DATA-DED-DED-NT-PD (1) TO TWA-DED-NOT-PD-IN
      *DB2 ELSE
      *DB2    MOVE ZEROS TO TWA-DED-NOT-PD-IN.
      
           MOVE T-M-BAS-EE-MAST-REC-CODE     TO TWA-REC-TYPE-IN.
      *DB2 MOVE M-BAS-DATA-MAST-REC-CODE     (1) TO TWA-REC-TYPE-IN.
      
           MOVE T-M-BAS-EE-ACT-CODE          TO TWA-ACTV-CODE-IN.
      *DB2 MOVE M-BAS-DATA-ACT-CODE          (1) TO TWA-ACTV-CODE-IN.
      
           MOVE T-M-BAS-EE-BILL-TYPE-CODE    TO TWA-BILL-TYPE-IN.
      *DB2 MOVE M-BAS-DATA-BILL-TYPE-CODE    (1) TO TWA-BILL-TYPE-IN.
      
           MOVE T-M-BAS-EE-BILL-FREQ-CODE    TO TWA-BILL-FREQ-IN.
      *DB2 MOVE M-BAS-DATA-BILL-FREQ-CODE    (1) TO TWA-BILL-FREQ-IN.
      
           MOVE T-M-BAS-EE-MAR-STAT-CODE     TO TWA-MAR-STAT-IN.
      *DB2 MOVE M-BAS-DATA-MAR-STAT-CODE     (1) TO TWA-MAR-STAT-IN.
      
           SKIP3
           IF  TRMDT-IND = +0
             IF  T-M-BAS-EE-TERM-ACT-DATE   IS NUMERIC  AND
                 T-M-BAS-EE-TERM-ACT-DATE   GREATER THAN ZERO
                   MOVE T-M-BAS-EE-TERM-ACT-DATE  TO  W-DATE
                   PERFORM C9000-VALDT
                   MOVE W-DATE9                 TO TWA-TERM-ACT-DATE-IN
             ELSE
                 MOVE ZEROS TO TWA-TERM-ACT-DATE-IN.
      
      *DB2 IF  M-BAS-DATA-TERM-ACT-DATE (1)  IS NUMERIC  AND
      *DB2     M-BAS-DATA-TERM-ACT-DATE (1)  GREATER THAN ZERO
      *DB2     MOVE M-BAS-DATA-TERM-ACT-DATE (1)
      *DB2                                    TO TWA-TERM-ACT-DATE-IN
      *DB2 ELSE
      *DB2     MOVE ZEROS TO TWA-TERM-ACT-DATE-IN.
            SKIP3
      
           MOVE T-M-BAS-EE-NAT-CODE          TO TWA-NAT-CODE-IN.
      *DB2 MOVE M-BAS-DATA-NAT-CODE          (1) TO TWA-NAT-CODE-IN.
      
           MOVE T-M-BAS-EE-SEX-CODE          TO TWA-SEX-CODE-IN.
      *DB2 MOVE M-BAS-DATA-SEX-CODE          (1) TO TWA-SEX-CODE-IN.
      
           IF ( EMPLER-IND = +0 )          AND
              ( T-M-BAS-EE-EMPLOYER-NUM )   >   0
              MOVE T-M-BAS-EE-EMPLOYER-NUM  TO W-ER-REG-NUM
              MOVE W-ER-REG-NUM             TO TWA-ER-REG-NUM-IN
           ELSE
           IF ( REGNUM-IND = +0 )          AND
              ( T-M-BAS-EE-SEC-REG-NUM )    >   0
              MOVE T-M-BAS-EE-SEC-REG-NUM   TO W-ER-REG-NUM
              MOVE W-ER-REG-NUM             TO TWA-ER-REG-NUM-IN
           ELSE
              MOVE ZEROES                   TO W-ER-REG-NUM
              MOVE W-ER-REG-NUM             TO TWA-ER-REG-NUM-IN.
      
      *       MOVE T-M-BAS-EE-EMPLOYER-NUM  TO TWA-ER-REG-NUM-IN.
      *DB2 MOVE M-BAS-DATA-ER-REG-NUM        (1) TO TWA-ER-REG-NUM-IN.
      
           MOVE T-M-BAS-EE-BILL-DAY          TO TWA-COLL-DAY-IN.
      *DB2 MOVE M-BAS-DATA-BILL-DAY          (1) TO TWA-COLL-DAY-IN.
      
           MOVE T-M-BAS-EE-PIS-NUM           TO TWA-PIS-NUM-IN.
      *DB2 MOVE M-BAS-DATA-PIS-NUM           (1) TO TWA-PIS-NUM-IN.
      
           IF NEFFDT-IND = +0
             MOVE T-M-BAS-EE-NAT-EFF-DATE   TO W-DATE
             PERFORM C9000-VALDT
             MOVE W-DATE9                   TO TWA-NAT-EFF-DATE-IN.
      *DB2 MOVE M-BAS-DATA-NAT-EFF-DATE      (1) TO TWA-NAT-EFF-DATE-IN.

           IF NDRPDT-IND = +0
             MOVE T-M-BAS-EE-DROP-NAT-DATE  TO W-DATE
             PERFORM C9000-VALDT
             MOVE W-DATE9                   TO TWA-DROP-NAT-DATE-IN1
             MOVE TWA-DROP-NAT-DATE-IN1     TO TWA-DROP-NAT-DATE-IN
             MOVE  DFHRED                   TO NTDRPYYC
                                               NTDRPMMC
                                               NTDRPDDC
                                               NATNLTYC
           ELSE
             MOVE ZEROS                     TO TWA-DROP-NAT-DATE-IN.


           IF CEXPDT-IND = +0
             MOVE T-M-BAS-EE-CV-EXP-DATE  TO W-DATE
             PERFORM C9000-VALDT
             MOVE W-DATE9                   TO TWA-CIV-EXP-DATE-IN1
             MOVE TWA-CIV-EXP-DATE-IN1     TO TWA-CIV-EXP-DATE-IN
             MOVE  DFHRED                   TO CIVEXPYC
                                               CIVEXPMC
                                               CIVEXPDC
           ELSE
             MOVE ZEROS                     TO TWA-CIV-EXP-DATE-IN.

      
           MOVE 'OOP9020P' TO TCAPCPI.
      
           EXEC  CICS  LINK  PROGRAM (TCAPCPI)
                               RESP  (W-RESP)
           END-EXEC.
      
           IF  W-RESP = DFHRESP (NORMAL)
               IF  RETURN-ZERO
                   NEXT SENTENCE
               ELSE
                   MOVE '601' TO TCADCDC1
                   PERFORM S0400-DUMP-XCTL
           ELSE
               MOVE '602' TO TCADCDC1
               PERFORM S0400-DUMP-XCTL.
      
      
           CALL 'CCOBADDR'  USING  TWA-FLIP-B-LENGTH  FLIP-PTR.
           MOVE  FLIP-PTR   TO  TCTTE-ADDR4.
      
           MOVE  FLIP-PTR            TO  TCTTE-ADDR4.
           ADD   FLIP-PTR  2     GIVING  TCTTE-ADDR2.
      **   ADD   FLIP-PTR  89    GIVING  TCTTE-ADDR3.
      **   ADD   FLIP-PTR  2  98 GIVING  TCTTE-ADDR3.
      
      *TAH ADD   FLIP-PTR  2 100 GIVING  TCTTE-ADDR3.
      *ZAI ADD   FLIP-PTR  2 101 GIVING  TCTTE-ADDR3.
      *    ADD   FLIP-PTR  2 103 GIVING  TCTTE-ADDR3.
           ADD   FLIP-PTR  2 119 GIVING  TCTTE-ADDR3.
      
      *TAH MOVE  100  TO  TWA-FLIP-B-LENGTH.
      *ZAI MOVE  101  TO  TWA-FLIP-B-LENGTH.
      *    MOVE  103  TO  TWA-FLIP-B-LENGTH.
           MOVE  119  TO  TWA-FLIP-B-LENGTH.
      
      **   MOVE  87   TO  TWA-FLIP-B-LENGTH.
      **   MOVE  98   TO  TWA-FLIP-B-LENGTH.
      
           MOVE 'OOP9020P' TO TCAPCPI.
      
           EXEC  CICS  LINK  PROGRAM (TCAPCPI)
                               RESP  (W-RESP)
           END-EXEC.
      
           IF  W-RESP = DFHRESP (NORMAL)
               IF  RETURN-ZERO
                   NEXT SENTENCE
               ELSE
                   MOVE '605' TO TCADCDC1
                   PERFORM S0400-DUMP-XCTL
           ELSE
               MOVE '606' TO TCADCDC1
               PERFORM S0400-DUMP-XCTL.

       C0600-FLIP-EXIT.  EXIT.

       C0750-DATE-TIME SECTION.

           MOVE FUNCTION CURRENT-DATE TO GREG-DATE
           MOVE FUNCTION REVERSE(GREG-DATE) TO W-CUR-DATE
           MOVE W-CUR-DATE TO CDATEO

           EXEC CICS
                ASKTIME
           END-EXEC.
           MOVE EIBTIME  TO W-TIME
           MOVE FUNCTION REVERSE(W-TIME) TO CTIMEO
           INSPECT CTIMEO CONVERTING '/' TO ':'.

       C0750-DATE-TIME-EXIT.
           EXIT.

       D0000-FINAL SECTION.
           SKIP1
           MOVE  K-PF10-11                 TO ERRMSG1O.
           MOVE  DFHNEUTR                  TO ERRMSG1C.
           SKIP1
      
           PERFORM C0750-DATE-TIME.

           EXEC CICS SEND MAP ('MAP01   ')
                          MAPSET ('ORM1511')
                          FROM  (MAP01O)
                          ERASE  CURSOR  FREEKB
           END-EXEC.

       D0000-FINAL-RETURN.
      
           MOVE '1511' TO TCANXTID.
           MOVE '1'    TO TCTTE-ENTRY-COUNT.
           EXEC CICS RETURN
                TRANSID (TCANXTID)
           END-EXEC.

       D0000-FINAL-EXIT.
           EXIT.

       S0400-DUMP-XCTL SECTION.
      
           EXEC CICS DUMP
                   DUMPCODE (TCADCDC)
           END-EXEC.
      
           MOVE HIGH-VALUES TO TCTTE-EXIT-SW.
           MOVE HIGH-VALUES TO TCTTE-ENTRY-SW.
           MOVE 'ORP1500P'  TO TCAPCPI.
           PERFORM S0500-XCTL.

       S0400-DUMP-XCTL-EXIT.
           EXIT.

       S0500-XCTL SECTION.
      
           EXEC CICS XCTL PROGRAM (TCAPCPI)
           END-EXEC.

       S0500-XCTL-EXIT.
            EXIT.

       C9000-VALDT     SECTION.
      *-----------------------*
      
           MOVE W-YEAR TO W-YEAR9
           MOVE W-MNTH TO W-MNTH9
           MOVE W-DAY  TO W-DAY9.

       C9000-VALDT-EXIT.
           EXIT.

       DB2-ERROR         SECTION.
      *-------------------------*
           IF NOT (SQLCODE = +0 OR +100)
              MOVE SQLCA TO ORSS0400-SQLCA
              EXEC CICS
                   SYNCPOINT ROLLBACK
              END-EXEC
      *
              MOVE 'SSS'               TO ORSS0400-SYSID
              MOVE TWANUM              TO ORSS0400-SSN
      *
              MOVE TCTTE-CURNT-TRAN-ID TO ORSS0400-TRNID
              MOVE TCTTE-DEPT          TO ORSS0400-CLERK(1:2)
              MOVE TCTTE-CLERK         TO ORSS0400-CLERK(3:3)
              MOVE W-EIBDS             TO ORSS0400-TABNM
              EXEC CICS
                   LINK
                   PROGRAM ('ORSS0400')
                   COMMAREA(ORSS0400-AREA)
                   LENGTH  (LENGTH OF ORSS0400-AREA)
              END-EXEC
              MOVE ORSS0400-SQLCD                   TO W-SQLCD
              MOVE FUNCTION REVERSE(W-SQLCD-C(7:4)) TO ABEND-ERR-CODE
              MOVE FUNCTION REVERSE(W-EIBDS)        TO ABEND-ERR-EIBDS
              MOVE 'Ýáã Úã ÃØÎ'                     TO ABEND-ERR-TEXT
      *
              MOVE ATT-PROT-HILITE                  TO ERRMSG1A
              MOVE ABEND-ERR-MSG                    TO ERRMSG1O
              PERFORM D0000-FINAL
           END-IF.

       DB2-ERROR-EXIT.
           EXIT.

           EXIT PROGRAM.
