      ******************************************************************
      * Created: Tue, 5 Mar 2024 10:02:42 GMT
      * Generated by: IBM watsonx Code Assistant for Z Refactoring
      * Assistant
      * Workbook name: new
      * Workbook id: 3be9ffc2-fa80-48a3-b497-0aca679973d6
      * Project: $clientCOBOL_425b64bc-af6b-4d20-91da-eb694d49ef1b
      ******************************************************************

       IDENTIFICATION DIVISION.
       PROGRAM-ID. WBEXPORT.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  W-EIBDS                   PIC X(30).
       01  W-SQLCD                   PIC Z(09)-.
       01  ABEND-ERR-MSG.
           02 ABEND-ERR-CODE          PIC X(04).
           02 ABEND-ERR-TEXT          PIC X(10).
           02 ABEND-ERR-EIBDS         PIC X(30).
       01  W-SQLCD-C REDEFINES W-SQLCD
                                     PIC X(10).
       01  ORSS0400-AREA.
           02 ORSS0400-SYSID          PIC  X(03).
           02 ORSS0400-CLERK          PIC  X(05).
           02 ORSS0400-TABNM          PIC  X(30).
           02 ORSS0400-SSN            PIC  9(12).
           02 ORSS0400-SSN-X REDEFINES ORSS0400-SSN
                                    PIC  X(12).
           02 ORSS0400-TRNID          PIC  X(04).
           02 ORSS0400-SQLCA          PIC X(136).
           02 F REDEFINES ORSS0400-SQLCA.
              03 F1                   PIC  X(12).
              03 ORSS0400-SQLCD       PIC S9(09)   COMP.
              03 F2                   PIC  X(120).

           EXEC SQL
             INCLUDE SQLCA
           END-EXEC.

       LINKAGE SECTION.

       PROCEDURE DIVISION.
       S0600-GET-ACCOUNT-NUMBER    SECTION.

           MOVE 'LT_ACCOUNTS1          ' TO W-EIBDS.
           MOVE  01                     TO T-ACCT-ORG-CODE.

           EXEC SQL
                 SELECT   ACCT_CODE, ACCT_NAME
                 INTO    :T-ACCT-CODE
                FROM  LT_ACCOUNTS
                WHERE ACCT_NAME                     =
                      :T-ACCT-NAME
                AND   ACCT_ORG_CODE                 =
                      :T-ACCT-ORG-CODE
                AND   ACCT_CODE_STATUS       IN(' ' , '0')
                ORDER BY
                      ACCT_CODE
                FETCH FIRST 1 ROW ONLY
           END-EXEC.

           PERFORM DB2-ERROR.

           IF SQLCODE = +0
                MOVE T-ACCT-CODE
                                TO C-PEX-ATBL-NUM      (C-PEX-ATBL-NDX)
              ELSE
                MOVE ZEROES     TO C-PEX-ATBL-NUM      (C-PEX-ATBL-NDX).

       DB2-ERROR            SECTION.

           IF NOT (SQLCODE = +0 OR +100)

              MOVE SQLCA TO ORSS0400-SQLCA

              EXEC CICS
                   SYNCPOINT ROLLBACK
              END-EXEC

              MOVE 'SSS'               TO ORSS0400-SYSID
              COMPUTE ORSS0400-SSN = FUNCTION NUMVAL(TRAN-LEAD-SSN-KEY)
              MOVE TCTTE-CURNT-TRAN-ID TO ORSS0400-TRNID
              MOVE TCTTE-DEPT          TO ORSS0400-CLERK(1:2)
              MOVE TCTTE-CLERK         TO ORSS0400-CLERK(3:3)
              MOVE W-EIBDS             TO ORSS0400-TABNM

              EXEC CICS
                   LINK
                   PROGRAM ('ORSS0400')
                   COMMAREA(ORSS0400-AREA)
                   LENGTH  (LENGTH OF ORSS0400-AREA)
              END-EXEC

              MOVE ORSS0400-SQLCD                   TO W-SQLCD
              MOVE FUNCTION REVERSE(W-SQLCD-C(7:4)) TO ABEND-ERR-CODE
              MOVE FUNCTION REVERSE(W-EIBDS)        TO ABEND-ERR-EIBDS
              MOVE '¯×Ã ïÙ ïäá'                     TO ABEND-ERR-TEXT
              MOVE ORSS0400-SQLCA                   TO SQLCA

           END-IF.

       DB2-ERROR-EXIT.      EXIT.

           EXIT PROGRAM.
