      ******************************************************************
      * Created: Tue, 20 Feb 2024 13:22:10 GMT
      * Generated by: IBM watsonx Code Assistant for Z Refactoring
      * Assistant
      * Workbook name: test
      * Workbook id: 667ceb4d-fb4b-40fa-8e00-f0e592364be6
      * Project: $clientCOBOL_8ee4fe22-86f7-44fd-b691-17e354abffe8
      ******************************************************************

       IDENTIFICATION DIVISION.
       PROGRAM-ID. WBEXPOR.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01  ABEND-ERR-MSG.
           02 ABEND-ERR-TEXT          PIC X(10).
           02 F-1                       PIC X(01) VALUE SPACES.
           02 ABEND-ERR-EIBDS         PIC X(30).
           02 F-2                       PIC X(01) VALUE SPACES.
           02 F-3                       PIC X(05) VALUE 'åÒãÑ '.
           02 F-5                       PIC X(01) VALUE SPACES.
           02 ABEND-ERR-CODE          PIC X(04).
       01  ORSS0400-AREA.
           02 ORSS0400-SQLCA          PIC X(136).
           02 F-4 REDEF-4INES ORSS0400-SQLCA.
              03 F1                   PIC  X(12).
              03 ORSS0400-SQLCD       PIC S9(09)   COMP.
              03 F2                   PIC  X(120).
           02 ORSS0400-SYSID          PIC  X(03).
           02 ORSS0400-CLERK          PIC  X(05).
           02 ORSS0400-TABNM          PIC  X(30).
           02 ORSS0400-SSN            PIC  9(12).
           02 ORSS0400-SSN-X REDEFINES ORSS0400-SSN
                                      PIC  X(12).
           02 ORSS0400-TRNID          PIC  X(04).
       01  GREG-DATE                  PIC X(08).
       01  W-SQLCD                      PIC Z(09)-.
       01  W-CUR-DATE                 PIC X(02)/X(02)/X(04).
       01  W-SQLCD-C REDEFINES W-SQLCD  PIC X(10).
       01  W-TIME                     PIC 99/99/99.
       01  W-EIBDS                     PIC X(30).
       01 TCA-FIELD.
           05  TCANXTID                  PIC X(04) VALUE SPACES.
       01  CONSTANTS.
             05  K-PF10-11.
              10  FILLER                      PIC X(70)  VALUE
                 'åáæÍãáÇ ÛáÇÈãáÇ äÚ ÑÇÓÝÊÓáÇ/ 01ÝÈ ÊÇßíÔáÇ äÚ ÑÇÓÝÊÓáÇ
      -           'ÝÈ ßæäÈáá11 '.

           EXEC SQL
             INCLUDE SQLCA
           END-EXEC.

       LINKAGE SECTION.

       PROCEDURE DIVISION.
       C0550-BUILD-BANK-INFO SECTION.
      
           MOVE LOW-VALUES TO TWARDSW.
      
           MOVE 'ST_MST_BANK_PAY'  TO  W-EIBDS.
           MOVE TWANUM             TO  T-M-BANK-PAY-SSN.
      
           EXEC SQL
                SELECT  M_BANK_PAY_METHOD_CODE      ,
                        M_BANK_PAY_PAYEE_ACCT_NUM   ,
                        M_BANK_PAY_BANK_CODE        ,
                        M_BANK_PAY_BANK_BR_AGY_CODE
                INTO  :T-M-BANK-PAY-METHOD-CODE     ,
                      :T-M-BANK-PAY-PAYEE-ACCT-NUM  ,
                      :T-M-BANK-PAY-BANK-CODE       ,
                      :T-M-BANK-PAY-BANK-BR-AGY-CODE
                FROM ST_MST_BANK_PAY
                WHERE
                    M_BANK_PAY_SSN   =  :T-M-BANK-PAY-SSN
                                    AND
                    M_BANK_PAY_END_DATE IS NULL
                ORDER BY M_BANK_PAY_SSN ,
                         M_BANK_PAY_TRLR_SEQ_NUM DESC
                 FETCH FIRST 1 ROW ONLY
      
            END-EXEC.
      
                PERFORM DB2-ERROR.
                IF SQLCODE  =  +0
                   NEXT SENTENCE
                ELSE
                IF SQLCODE  =  +100
                   MOVE 'ÏæÌæã ÑíÛ ßäÈáÇ áÌÓ '      TO ERRMSG1O
                ELSE
                   MOVE  HIGH-VALUES                TO TWAERROR
                   MOVE 'ßäÈáÇ Ýáã Úã áãÇÚÊáÇÈ ÃØÎ' TO ERRMSG1O
                   PERFORM D0000-FINAL
                END-IF.                                                
           00010900.

       C0750-DATE-TIME SECTION.

           MOVE FUNCTION CURRENT-DATE TO GREG-DATE
           MOVE FUNCTION REVERSE(GREG-DATE) TO W-CUR-DATE
           MOVE W-CUR-DATE TO CDATEO

           EXEC CICS
                ASKTIME
           END-EXEC.
           MOVE EIBTIME  TO W-TIME
           MOVE FUNCTION REVERSE(W-TIME) TO CTIMEO
           INSPECT CTIMEO CONVERTING '/' TO ':'.

       C0750-DATE-TIME-EXIT.
           EXIT.

       D0000-FINAL SECTION.
           SKIP1
           MOVE  K-PF10-11                 TO ERRMSG1O.
           MOVE  DFHNEUTR                  TO ERRMSG1C.
           SKIP1
      
           PERFORM C0750-DATE-TIME.

           EXEC CICS SEND MAP ('MAP01   ')
                          MAPSET ('ORM1511')
                          FROM  (MAP01O)
                          ERASE  CURSOR  FREEKB
           END-EXEC.

       D0000-FINAL-RETURN.
      
           MOVE '1511' TO TCANXTID.
           MOVE '1'    TO TCTTE-ENTRY-COUNT.
           EXEC CICS RETURN
                TRANSID (TCANXTID)
           END-EXEC.

       D0000-FINAL-EXIT.
           EXIT.

       DB2-ERROR         SECTION.
      *-------------------------*
           IF NOT (SQLCODE = +0 OR +100)
              MOVE SQLCA TO ORSS0400-SQLCA
              EXEC CICS
                   SYNCPOINT ROLLBACK
              END-EXEC
      *
              MOVE 'SSS'               TO ORSS0400-SYSID
              MOVE TWANUM              TO ORSS0400-SSN
      *
              MOVE TCTTE-CURNT-TRAN-ID TO ORSS0400-TRNID
              MOVE TCTTE-DEPT          TO ORSS0400-CLERK(1:2)
              MOVE TCTTE-CLERK         TO ORSS0400-CLERK(3:3)
              MOVE W-EIBDS             TO ORSS0400-TABNM
              EXEC CICS
                   LINK
                   PROGRAM ('ORSS0400')
                   COMMAREA(ORSS0400-AREA)
                   LENGTH  (LENGTH OF ORSS0400-AREA)
              END-EXEC
              MOVE ORSS0400-SQLCD                   TO W-SQLCD
              MOVE FUNCTION REVERSE(W-SQLCD-C(7:4)) TO ABEND-ERR-CODE
              MOVE FUNCTION REVERSE(W-EIBDS)        TO ABEND-ERR-EIBDS
              MOVE 'Ýáã Úã ÃØÎ'                     TO ABEND-ERR-TEXT
      *
              MOVE ATT-PROT-HILITE                  TO ERRMSG1A
              MOVE ABEND-ERR-MSG                    TO ERRMSG1O
              PERFORM D0000-FINAL
           END-IF.

       DB2-ERROR-EXIT.
           EXIT.

           EXIT PROGRAM.
